AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  CognitoUserPoolId:
    Type: String
    Description: "ID del User Pool de Cognito"
  CognitoClientId:
    Type: String
    Description: "ID del Cliente de la aplicación en Cognito"
  CognitoDomain:
    Type: String
    Description: "Dominio de Cognito"
  DbUser:
    Type: String
    Description: "Usuario de la base de datos"
  DbPassword:
    Type: String
    Description: "Contraseña de la base de datos"
  DbHost:
    Type: String
    Description: "Host de la base de datos"
  DbPort:
    Type: String
    Description: "Puerto de la base de datos"
  DbName:
    Type: String
    Description: "Nombre de la base de datos"

Resources:
  KuoselLambdaLith:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kuosel-lambdalith
      Handler: main.handler  # Asegúrate de que el handler apunte correctamente a `main.py`
      Runtime: python3.11
      CodeUri: .       # La carpeta donde está el código y las dependencias
      MemorySize: 128
      Timeout: 30
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref CognitoUserPoolId
          COGNITO_CLIENT_ID: !Ref CognitoClientId
          COGNITO_DOMAIN: !Ref CognitoDomain
          DB_USER: !Ref DbUser
          DB_PASSWORD: !Ref DbPassword
          DB_HOST: !Ref DbHost
          DB_PORT: !Ref DbPort
          DB_NAME: !Ref DbName
          PYTHONPATH: "/var/task/dependencies:/var/task"  # Añade dependencies al PYTHONPATH
      Policies:
        - AWSLambdaBasicExecutionRole  # Asigna permisos básicos de ejecución