AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  KuoselLambdaLith:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: kuosel-lambdalith  # Nombre de la función Lambda existente
      Handler: main.handler
      Runtime: python3.11
      CodeUri: package/
      MemorySize: 128
      Timeout: 30
