name: Deploy FastAPI Lambda

# Disparadores: cuando se hace push a la rama main
on:
  push:
    branches:
      - main

# Definir los trabajos del flujo
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del código fuente
      - name: Check out the repository
        uses: actions/checkout@v3

      # 2. Configurar Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Instalar dependencias en la carpeta dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p dependencies
          pip install -r requirements.txt -t dependencies/

      # 4. Empaquetar la aplicación Lambda usando AWS SAM
      - name: Package SAM application
        run: |
          mkdir -p package
          cp -r dependencies package/dependencies
          cp -r app/* package/src/
          cp main.py package/
          cd package && zip -r ../deployment-package.zip .

      # 5. Configurar AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
          aws-region: us-east-2

      # 6. Desplegar la función Lambda
      - name: Deploy with SAM
        run: |
          sam build
          sam deploy --resolve-s3 --no-confirm-changeset --stack-name kuosel-lambdalith --capabilities CAPABILITY_IAM

      # 7. Limpiar archivos temporales
      - name: Clean up temporary files
        run: rm -rf package/ dependencies/ deployment-package.zip
